In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"/Users/mohammadehsan/Desktop/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df=df.drop(columns=['Name', 'Ticket', 'Cabin'])
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0000,S
887,888,1,1,female,19.0,0,0,30.0000,S
888,889,0,3,female,NaN,1,2,23.4500,S
889,890,1,1,male,26.0,0,0,30.0000,C
890,891,0,3,male,32.0,0,0,7.7500,Q

In [4]:
df["Sex"]=df["Sex"].map({"male":0,"female":1})
df

     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0              1         0       3    0  22.0      1      0   7.2500        S
1              2         1       1    1  38.0      1      0  71.2833        C
2              3         1       3    1  26.0      0      0   7.9250        S
3              4         1       1    1  35.0      1      0  53.1000        S
4              5         0       3    0  35.0      0      0   8.0500        S
..           ...       ...     ...  ...   ...    ...    ...      ...      ...
886          887         0       2    0  27.0      0      0  13.0000        S
887          888         1       1    1  19.0      0      0  30.0000        S
888          889         0       3    1   NaN      1      2  23.4500        S
889          890         1       1    0  26.0      0      0  30.0000        C
890          891         0       3    0  32.0      0      0   7.7500        Q

[891 rows x 9 columns]

In [5]:
print(df['Age'].head())
print("Age mean:", df['Age'].mean())
print("Age type:", df['Age'].dtype)
print("Nulls in Age:", df['Age'].isnull().sum())
df

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64
Age mean: 29.69911764705882
Age type: float64
Nulls in Age: 177

     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0              1         0       3    0  22.0      1      0   7.2500        S
1              2         1       1    1  38.0      1      0  71.2833        C
2              3         1       3    1  26.0      0      0   7.9250        S
3              4         1       1    1  35.0      1      0  53.1000        S
4              5         0       3    0  35.0      0      0   8.0500        S
..           ...       ...     ...  ...   ...    ...    ...      ...      ...
886          887         0       2    0  27.0      0      0  13.0000        S
887          888         1       1    1  19.0      0      0  30.0000        S
888          889         0       3    1   NaN      1      2  23.4500        S
889          890         1       1    0  26.0      0      0  30.0000        C
890          891         0       3    0  32.0      0      0   7.7500        Q

[891 rows x 9 columns]

In [6]:
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

/var/folders/1q/2_r5ckf54s3fskzjg6wx91fc0000gn/T/ipykernel_1769/585847971.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

In [7]:
df["Embarked"]=df["Embarked"].map({"S":0,"C":1,"Q":2})
df

     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0              1         0       3    0  22.0      1      0   7.2500         0
1              2         1       1    1  38.0      1      0  71.2833         1
2              3         1       3    1  26.0      0      0   7.9250         0
3              4         1       1    1  35.0      1      0  53.1000         0
4              5         0       3    0  35.0      0      0   8.0500         0
..           ...       ...     ...  ...   ...    ...    ...      ...       ...
886          887         0       2    0  27.0      0      0  13.0000         0
887          888         1       1    1  19.0      0      0  30.0000         0
888          889         0       3    1   NaN      1      2  23.4500         0
889          890         1       1    0  26.0      0      0  30.0000         1
890          891         0       3    0  32.0      0      0   7.7500         2

[891 rows x 9 columns]

In [32]:
invalid_ages = df[~df["Age"].apply(lambda x: str(x).replace('.', '', 1).isdigit())]
print(invalid_ages)

df["Age"] = pd.to_numeric(df["Age"], errors='coerce')
df["Age"].fillna(df["Age"].mean(), inplace=True)

     PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked
0              1         0       3    0  NaN      1      0   7.2500         0
1              2         1       1    1  NaN      1      0  71.2833         1
2              3         1       3    1  NaN      0      0   7.9250         0
3              4         1       1    1  NaN      1      0  53.1000         0
4              5         0       3    0  NaN      0      0   8.0500         0
..           ...       ...     ...  ...  ...    ...    ...      ...       ...
886          887         0       2    0  NaN      0      0  13.0000         0
887          888         1       1    1  NaN      0      0  30.0000         0
888          889         0       3    1  NaN      1      2  23.4500         0
889          890         1       1    0  NaN      0      0  30.0000         1
890          891         0       3    0  NaN      0      0   7.7500         2

[891 rows x 9 columns]

/var/folders/1q/2_r5ckf54s3fskzjg6wx91fc0000gn/T/ipykernel_1769/2872524915.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

In [16]:
X=df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]
y=df["Survived"]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [13]:
print(X_train.isnull().sum())

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      0
dtype: int64